-   id: dockerlint
    name: dockerlint
    entry: dockerlint
    language: node
    files: Dockerfile
    args: []

    # Use additional_dependencies to install the actual node package
    additional_dependencies: ['dockerlint@0.1.0']
    minimum_pre_commit_version: 0.7.0
